name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Check for package-lock.json
      id: check-lock
      run: |
        if [ -f "package-lock.json" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    - name: Install dependencies (with package-lock.json)
      if: steps.check-lock.outputs.exists == 'true'
      run: npm ci

    - name: Install dependencies (without package-lock.json)
      if: steps.check-lock.outputs.exists == 'false'
      run: |
        npm install
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package-lock.json
        git commit -m "Add package-lock.json" || echo "No changes to commit"
        git push

    - name: Build
      run: npm run build

    - name: Add .nojekyll file
      run: touch ./out/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
